export interface Activities{
    id: string,
    title: string,
    paymentStatus: string,
    company: string,
    type: string,
    typeValue: string,
  price: string,
  viewColor: string,
  textcolor: string
}

export const DATA: Activities[] = [
  {
    id: '1',
    title: 'Kitchen Renovation',
    paymentStatus: 'Overdue',
    company: 'Smith & Co Builders',
    type: 'Invoice: ',
    typeValue: 'INV-2025-001',
    price: '£549.50',
    viewColor: '#F0535312',
    textcolor: '#F05353',
  },
  {
    id: '2',
    title: 'Bathroom Plumbing',
    paymentStatus: 'Sent',
    company: 'Ryan & Peter Holders',
    type: 'Quote: ',
    typeValue: 'QT-2025-001',
    price: '£399.00',
    viewColor: '#FFC81412',
    textcolor: '#FFC814',
  },
  {
    id: '3',
    title: 'Floor Work',
    paymentStatus: 'Paid',
    company: 'GreenTech Ltd.',
    type: 'Invoice: ',
    typeValue: 'INV-2025-001',
    price: '£549.50',
    viewColor: '#3AB48912',
    textcolor: '#3AB489',
  },
  {
    id: '4',
    title: 'Floor Work',
    paymentStatus: 'Paid',
    company: 'GreenTech Ltd.',
    type: 'Invoice: ',
    typeValue: 'INV-2025-001',
    price: '£549.50',
    viewColor: '#3AB48912',
    textcolor: '#3AB489',
  },
  {
    id: '5',
    title: 'Floor Work',
    paymentStatus: 'Paid',
    company: 'GreenTech Ltd.',
    type: 'Invoice: ',
    typeValue: 'INV-2025-001',
    price: '£549.50',
    viewColor: '#3AB48912',
    textcolor: '#3AB489',
  },
];