export const images = {
  img_bg: require('@assets/images/img_bg.png'),
  img_logo: require('@assets/images/img_logo.png'),
  img_vector: require('@assets/images/img_vector.png'),
  img_intro: require('@assets/images/img_intro.png'),
  img_onboarding: require('@assets/images/img_onboarding.png'),
  img_profile: require('@assets/images/img_profile.png'),
  img_camera: require('@assets/images/img_camera.png'),
  img_brandcolor: require('@assets/images/img_brandcolor.png'),
  img_address: require('@assets/images/img_address.png'),
  img_gradient: require('@assets/images/img_gradient.png'),
  img_pro: require('@assets/images/img_pro.png'),
  img_subscription: require('@assets/images/img_subscription.png'),
  img_status: require('@assets/images/img_status.png'),
  img_lightintro: require('@assets/images/img_lightintro.png'),
  img_darklist: require('@assets/images/img_darklist.png'),
  img_darkprofile: require('@assets/images/img_darkprofile.png'),
  img_darkcamera: require('@assets/images/img_darkcamera.png'),
  img_darkstatus: require('@assets/images/img_darkstatus.png'),
  img_fileupload: require('@assets/images/img_fileupload.png'),
  img_quote: require('@assets/images/img_quote.png')
};