export const ENDPOINTS = {
  LOGIN: '/api/auth/login',
  SIGNUP: '/api/auth/signup',
  FORGOTPASSWORD: '/api/auth/forgot-password',
  PROFILESETUP: '/api/user/profile-setup',
  COMPANYPROFILESETUP: '/api/company',
  LOGOUT: '/api/auth/logout',
  SEARCHADDRESS: '/api/address/search',
  HOMESCREEN: '/api/home',
  QUOTELIST: '/api/quotes',
  CHANGEPASSWORD: '/api/auth/change-password',
  CREATECATEGORIES: '/api/categories',
  CREATESUBCATEGORIES: '/api/sub-categories',
  CREATEITEMS: '/api/item/create-or-update',
  FETCHITEMS: '/api/items',
  SECTIONS: '/api/proposal-document/sections',
  UPDATESTATUS: '/api/update-status',
  GETSECTIONS: '/api/proposal-document/sections',
  CRREATECLIENT: '/api/clients',
};