export const ENDPOINTS = {
  LOGIN: '/api/auth/login',
  SIGNUP: '/api/auth/signup',
  FORGOTPASSWORD: '/api/auth/forgot-password',
  PROFILESETUP: '/api/user/profile-setup',
  COMPANYPROFILESETUP: '/api/company',
  LOGOUT: '/api/auth/logout',
  SEARCHADDRESS: '/api/address/search',
  HOME: '/api/home',
  QUOTE: '/api/quotes',
  CHANGEPASSWORD: '/api/auth/change-password',
  CATEGORIES: '/api/categories',
  SUBCATEGORIES: '/api/sub-categories',
  ITEMS: '/api/item/create-or-update',
  FETCHITEMS: '/api/items',
  SECTIONS: '/api/proposal-document/sections',
  UPDATESTATUS: '/api/update-status',
  CLIENT: '/api/clients',
  INVOICE: '/api/invoices',
  TEAMMEMBER: '/api/company/users',
  PAYMENT: '/api/payments',
  PAYMENTDETAILS: '/api/payments/deposits',
  PAYMENTDEPOSITQUOTES: '/api/payment-deposit-quotes'
};